name: POS Workflows
run-name: ${{ github.actor }} POS Tests
on: [pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test